### ISSUE TITLE
i got some errors

### ISSUE THREAD

**Issue by serumanooo** [datatags/UltraCosmetics#119]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

i dont really know, i just woke up and found these erros in my console, i think i should report it there

### What was supposed to happen?

idk

### What happened instead?

these errors:
(see below)

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.3-RELEASE.jar

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

Im using WindSpigot  version 2.1.2 (if there is no support for this fork, could you make it?)

### What plugins do you have installed?

![image](https://github.com/datatags/UltraCosmetics/assets/132185379/19a93fb1-a530-4967-9123-96fa2f960f5b)
![image](https://github.com/datatags/UltraCosmetics/assets/132185379/ec92398c-9ed5-4e03-9981-2b49dccea7e1)
![image](https://github.com/datatags/UltraCosmetics/assets/132185379/1f65c561-9405-4d93-85e4-e409dd044d64)
(I printed it because i disabled the /plugins command, and i cant restart the server rn to enable it)

### Are there any errors in the console or in logs?

```
[11:12:51] [Craft Scheduler Thread - 3563/WARN]: Exception in thread "Craft Scheduler Thread - 3563" 
[11:12:51] [Craft Scheduler Thread - 3563/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24713009
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:12:52] [Server thread/INFO]: MADARA_NELAS_01 issued server command: /uc menu
[11:12:53] [Craft Scheduler Thread - 3610/WARN]: Exception in thread "Craft Scheduler Thread - 3610" 
[11:12:53] [Craft Scheduler Thread - 3610/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24714837
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:12:53] [Craft Scheduler Thread - 3611/WARN]: Exception in thread "Craft Scheduler Thread - 3611" 
[11:12:53] [Craft Scheduler Thread - 3611/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24714959
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:12:55] [Craft Scheduler Thread - 3567/WARN]: Exception in thread "Craft Scheduler Thread - 3567" 
[11:12:55] [Craft Scheduler Thread - 3567/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24717172
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:12:58] [Craft Scheduler Thread - 3612/WARN]: Exception in thread "Craft Scheduler Thread - 3612" 
[11:12:58] [Craft Scheduler Thread - 3612/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24720483
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:12:59] [Craft Scheduler Thread - 3614/WARN]: Exception in thread "Craft Scheduler Thread - 3614" 
[11:12:59] [Craft Scheduler Thread - 3614/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24721936
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:13:00] [Craft Scheduler Thread - 3613/WARN]: Exception in thread "Craft Scheduler Thread - 3613" 
[11:13:00] [Craft Scheduler Thread - 3613/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24722743
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:13:01] [Server thread/INFO]: yIceey issued server command: /party join oi122
[11:13:02] [Craft Scheduler Thread - 3615/WARN]: Exception in thread "Craft Scheduler Thread - 3615" 
[11:13:02] [Craft Scheduler Thread - 3615/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24724893
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:13:02] [Craft Scheduler Thread - 3616/WARN]: Exception in thread "Craft Scheduler Thread - 3616" 
[11:13:02] [Craft Scheduler Thread - 3616/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24725764
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:13:03] [Craft Scheduler Thread - 3617/WARN]: Exception in thread "Craft Scheduler Thread - 3617" 
[11:13:03] [Craft Scheduler Thread - 3617/WARN]: org.apache.commons.lang.UnhandledException: Plugin UltraCosmetics v3.3 generated an exception while executing task 24726462
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.bukkit.craftbukkit.v1_8_R3.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:516)
	at be.isach.ultracosmetics.util.BlockUtils.lambda$setToRestoreIgnoring$0(BlockUtils.java:157)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:65)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:55)
	... 3 more

[11:13:04] [Server thread/INFO]: antonio0347 issued server command: /p join oi122
[11:13:10] [Server thread/INFO]: ImLegend2000 issued server command: /uc menu
[11:13:10] [Server thread/INFO]: ImLegend2000 issued server command: /uc menu
[11:13:26] [Server thread/INFO]: Xxjulica issued server command: /ping
[11:13:32] [Server thread/INFO]: ImLegend2000 issued server command: /uc menu
[11:13:39] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to UltraCosmetics v3.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[WindSpigot-2.1.2.jar:]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:321) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:286) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:281) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:919) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:74) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7) ~[WindSpigot-2.1.2.jar:]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[WindSpigot-2.1.2.jar:]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.BlockFace.getDirection()Lorg/bukkit/util/Vector;
	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetPortalGun.handleClick(GadgetPortalGun.java:60) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetPortalGun.onRightClick(GadgetPortalGun.java:43) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.handleInteract(Gadget.java:286) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.lambda$onClick$5(UnmovableItemListener.java:133) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.lambda$forEachProviderWithItem$0(UnmovableItemListener.java:62) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.forEachProvider(UnmovableItemListener.java:54) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.forEachProviderWithItem(UnmovableItemListener.java:60) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.onClick(UnmovableItemListener.java:131) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot-2.1.2.jar:]
	... 19 more
[11:13:41] [Server thread/INFO]: AgeCheckk issued server command: /ping
[11:13:43] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to UltraCosmetics v3.3
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:299) ~[WindSpigot-2.1.2.jar:]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:67) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:511) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:496) ~[WindSpigot-2.1.2.jar:]
	at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:321) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:465) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1002) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:74) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:8) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:7) ~[WindSpigot-2.1.2.jar:]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:918) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:454) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:854) ~[WindSpigot-2.1.2.jar:]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:707) ~[WindSpigot-2.1.2.jar:]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
Caused by: java.lang.NoSuchMethodError: org.bukkit.block.BlockFace.getDirection()Lorg/bukkit/util/Vector;
	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetPortalGun.handleClick(GadgetPortalGun.java:60) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.gadgets.GadgetPortalGun.onRightClick(GadgetPortalGun.java:43) ~[?:?]
	at be.isach.ultracosmetics.cosmetics.gadgets.Gadget.handleInteract(Gadget.java:286) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.lambda$onClick$5(UnmovableItemListener.java:133) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.lambda$forEachProviderWithItem$0(UnmovableItemListener.java:62) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.forEachProvider(UnmovableItemListener.java:54) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.forEachProviderWithItem(UnmovableItemListener.java:60) ~[?:?]
	at be.isach.ultracosmetics.listeners.UnmovableItemListener.onClick(UnmovableItemListener.java:131) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:297) ~[WindSpigot-2.1.2.jar:]
	... 18 more
```

**Comment by datatags** [comment]
I'll fix the second error, but the first may be a result of a configuration error, could you upload your config?

**Comment by serumanooo** [comment]
> I'll fix the second error, but the first may be a result of a configuration error, could you upload your config?

yes here it is
https://drive.google.com/file/d/1HE_xBvOW-bIUypAdUfZ4PAt1UVar6b9F/view?usp=sharing

(maybe there is nothing wrong with my config now, because i found out that i was using the default config, and now i changed it to the config i use)

**Comment by datatags** [comment]
Both of these errors have now been fixed in code and should be resolved in the next dev build/update, thanks!
