### ISSUE TITLE
Opened chest area is there after restart

### ISSUE THREAD

**Issue by Superalex0102** [datatags/UltraCosmetics#136]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

While opening a chest, restart the server.

### What was supposed to happen?

The chest shouldn't be there

### What happened instead?

![image](https://github.com/datatags/UltraCosmetics/assets/41546701/77edf311-b2f5-4005-bf1c-8a100f4e81ae)

### What version of UltraCosmetics are you using? Do not say 'latest'.

UltraCosmetics-3.3-RELEASE

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

 This server is running Paper version git-Paper-388 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: fc9ee65 on ver/1.18.2

### What plugins do you have installed?

Not related

**Comment by datatags** [comment]
I've found the issue, but in the future please provide the errors you get in the console when experiencing an issue, for example in this case:
```
[Server thread/ERROR]: Error occurred while disabling UltraCosmetics v3.4 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:468) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d23
3d]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:196) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-9
5d233d]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:187) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-9
5d233d]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskLater(CraftScheduler.java:151) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-9
5d233d]
        at be.isach.ultracosmetics.util.EntitySpawner.spawnFireworks(EntitySpawner.java:133) ~[?:?]
        at be.isach.ultracosmetics.treasurechests.TreasureRandomizer.spawnFirework(TreasureRandomizer.java:152) ~[?:?]
        at be.isach.ultracosmetics.treasurechests.TreasureRandomizer.giveRandomThing(TreasureRandomizer.java:129) ~[?:?]
        at be.isach.ultracosmetics.treasurechests.TreasureChest.forceOpen(TreasureChest.java:175) ~[?:?]
        at be.isach.ultracosmetics.player.UltraPlayer.dispose(UltraPlayer.java:377) ~[?:?]
        at be.isach.ultracosmetics.player.UltraPlayerManager.dispose(UltraPlayerManager.java:68) ~[?:?]
        at be.isach.ultracosmetics.UltraCosmetics.shutdown(UltraCosmetics.java:439) ~[?:?]
        at be.isach.ultracosmetics.UltraCosmetics.onDisable(UltraCosmetics.java:418) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:367) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:501) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:493) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.disablePlugins(CraftServer.java:452) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:899) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.dedicated.DedicatedServer.t(DedicatedServer.java:717) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1086) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3491-Spigot-b081915-95d233d]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```
