### ISSUE TITLE
Can't use emotes and hats on 1.12.2

### ISSUE THREAD

**Issue by SHADOWDANCH** [datatags/UltraCosmetics#142]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Use latest paper 1.12.2 build
2. Use latest UltraCosmetics build
3. Try to equip hat or emote

### What was supposed to happen?

Hat or emote is equiped on player

### What happened instead?

Nothing happend in game and error appeared in server console.

### What version of UltraCosmetics are you using? Do not say 'latest'.

3.4.1

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

git-Paper-1620 (MC: 1.12.2)

### What plugins do you have installed?

UltraCosmetics

### Are there any errors in the console or in logs?

```
java.lang.NoSuchMethodError: 'boolean org.bukkit.inventory.meta.ItemMeta.hasAttributeModifiers()'
        at be.isach.ultracosmetics.cosmetics.ArmorCosmetic.writeAttributes(ArmorCosmetic.java:83)
        at be.isach.ultracosmetics.cosmetics.ArmorCosmetic.trySetSlot(ArmorCosmetic.java:73)
        at be.isach.ultracosmetics.cosmetics.ArmorCosmetic.tryEquip(ArmorCosmetic.java:54)
        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:80)
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:168)
        at ru.starfarm.lobby.cosmetics.menu.uc.HatMenu.openHatMenu$lambda$11$lambda$10$lambda$9(HatMenu.kt:110)
        at ru.starfarm.core.inventory.container.InventoryContainer$handlers$1$1.handle(InventoryContainer.kt:39)
        at ru.starfarm.core.inventory.container.InventoryContainer$handlers$1$1.handle(InventoryContainer.kt:34)
        at ru.starfarm.core.inventory.InventoryService._init_$lambda$6(InventoryService.kt:31)
        at ru.starfarm.core.event.EventContextKt$sam$i$java_util_function_Consumer$0.accept(EventContext.kt)
        at ru.starfarm.core.event.EventContextImpl.on$lambda$4(EventContextImpl.kt:39)
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
        at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

### Additional information that could be helpful in fixing the problem

ItemMeta#hasAttributeModifiers() does not exists in spigot api 1.12.2 ([ItemMeta](https://jd.papermc.io/paper/1.12/org/bukkit/inventory/meta/ItemMeta.html) 1.12.2 javadoc). 
Version check here https://github.com/datatags/UltraCosmetics/blob/2e935d5c01189a01880e03c6929a2bb8fa850837/core/src/main/java/be/isach/ultracosmetics/cosmetics/ArmorCosmetic.java#L39 should probably be changed to 1.13.

**Comment by datatags** [comment]
Thanks for the helpful info! 😄
