### ISSUE TITLE
Pets do not work properly on 1.12.2

### ISSUE THREAD

**Issue by SHADOWDANCH** [datatags/UltraCosmetics#143]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Use latest paper 1.12.2 build
2. Use latest UltraCosmetics build
3. Try to spawn any pet

### What was supposed to happen?

Pet spawned should have hologram and follow owner also no errors should appear in console log.

### What happened instead?

Pet spawned but without hologram and not following player. Multiple errors in console.

### What version of UltraCosmetics are you using? Do not say 'latest'.

3.4.1

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

git-Paper-1620 (MC: 1.12.2)

### What plugins do you have installed?

UltraCosmetics

### Are there any errors in the console or in logs?

```
java.lang.NoClassDefFoundError: org/bukkit/entity/Mob
    at be.isach.ultracosmetics.cosmetics.pets.Pet.setupNameTag(Pet.java:215)
    at be.isach.ultracosmetics.cosmetics.pets.Pet.initializeEntity(Pet.java:110)
    at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:89)
    at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:106)
    at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:168)
    at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:66)
    at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:31)
    at ru.starfarm.lobby.cosmetics.menu.uc.PetMenu.openPetMenu$lambda$11$lambda$10$lambda$9(PetMenu.kt:99)
    at ru.starfarm.core.inventory.container.InventoryContainer$handlers$1$1.handle(InventoryContainer.kt:39)
    at ru.starfarm.core.inventory.container.InventoryContainer$handlers$1$1.handle(InventoryContainer.kt:34)
    at ru.starfarm.core.inventory.InventoryService._init_$lambda$6(InventoryService.kt:31)
    at ru.starfarm.core.event.EventContextKt$sam$i$java_util_function_Consumer$0.accept(EventContext.kt)
    at ru.starfarm.core.event.EventContextImpl.on$lambda$4(EventContextImpl.kt:39)
    at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513)
    at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:2002)
    at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:33)
    at net.minecraft.server.v1_12_R1.PacketPlayInWindowClick.a(SourceFile:10)
    at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
    at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Mob
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:109)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:592)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
    ... 28 more
```

```
[UltraCosmetics] Task #1125 for UltraCosmetics v3.4.1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/entity/Mob
        at be.isach.ultracosmetics.cosmetics.pets.Pet.run(Pet.java:162) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[paper.jar:git-Paper-1620]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[paper.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:840) ~[paper.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[paper.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[paper.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[paper.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Mob
        ... 8 more
```

### Additional information that could be helpful in fixing the problem

Class `org.bukkit.entity.Mob` does not exists in spigot api 1.12.2 and was introduced only in 1.13. Also used pathfinding library ([MobChip](https://github.com/GamerCoder215/MobChip)) supports only 1.13+ so i don't see easy solution for this one.

**Comment by datatags** [comment]
Hmm, yeah, pets should be disabled outright on 1.12 and under since MobChip isn't available, I'll have to look into why it's still enabled

**Comment by datatags** [comment]
I tested with Paper 1.12.2 #1620 and UC 3.4.1, and the pets menu doesn't show up for me, and `/uc menu pets` and `/uc toggle pets ...` don't work either, so I'm not sure why they seem to be enabled for you. Does UC correctly identify the server version as 1.12 in the startup log? Also, could you upload your config so I can test with it?

**Comment by datatags** [comment]
Ping @SHADOWDANCH:

> I tested with Paper 1.12.2 #1620 and UC 3.4.1, and the pets menu doesn't show up for me, and `/uc menu pets` and `/uc toggle pets ...` don't work either, so I'm not sure why they seem to be enabled for you. Does UC correctly identify the server version as 1.12 in the startup log? Also, could you upload your config so I can test with it?

You can also join the discord to discuss this if you like: https://discord.gg/PgSXZT37JV
