### ISSUE TITLE
Can't open treasure chests

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#66]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Open main menu
2. Click on "Treasure Chests"

### What was supposed to happen?

Treasure chests should appear.

### What happened instead?

Nothing happened, error in console.

### What version of UltraCosmetics are you using? Do not say 'latest'.

(60868c9467e1beed380dc0a2ac84c493941c351c) UltraCosmetics-3.0-DEV-b2

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-296 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: f1583fc)

### What plugins do you have installed?

Plugins (8): Essentials, LibsDisguises, LuckPerms, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

```
[03:08:12 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v3.0-DEV-b2
java.lang.NoClassDefFoundError: Could not initialize class be.isach.ultracosmetics.treasurechests.TreasureChestManager
        at be.isach.ultracosmetics.menu.menus.MenuMain.lambda$putItems$3(MenuMain.java:185) ~[UltraCosmetics-3.0-DEV-b2.jar:?]
        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:132) ~[UltraCosmetics-3.0-DEV-b2.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor260.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-296]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3307) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:185) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.2.jar:git-Paper-296]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-296]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by datatags** [comment]
Did this happen after reloading the plugin or something?

**Comment by dennishzg** [comment]
No, I deleted the UltraCosmetics folder, compiled 60868c9467e1beed380dc0a2ac84c493941c351c and started the server. The treasurechests work when I use: https://github.com/datatags/UltraCosmetics/releases/tag/3.0-DEV-b2 or when I compile 3a7a3f53bfc0a36a3821221939801dcc6215d534 myself.
