### ISSUE TITLE
Kitty pet not working

### ISSUE THREAD

**Issue by dennishzg** [datatags/UltraCosmetics#75]
### Check if the issue is fixed in dev builds

- [X] I have confirmed that the issue is present on the latest dev build

### What steps will reproduce the issue?

1. Equip Kitty pet.

### What was supposed to happen?

Equip Kitty pet.

### What happened instead?

Not working, error in console.

### What version of UltraCosmetics are you using? Do not say 'latest'.

(bc44b67264cfbb0659e625d3fb7496328109b396) UltraCosmetics-3.0-DEV-b3b

### What server distribution (Spigot, Paper, etc.) and what version are you using? Do not say 'latest'.

This server is running Paper version git-Paper-345 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: e498dda)

### What plugins do you have installed?

Plugins (7): Essentials, LuckPerms, ProtocolLib, UltraCosmetics, Vault, WorldEdit, WorldGuard

### Are there any errors in the console or in logs?

```
[04:01:58 ERROR]: Could not pass event InventoryClickEvent to UltraCosmetics v3.0-DEV-b3b
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil1_19_R2.getObject(net.minecraft.world.entity.ai.goal.PathfinderGoal, String, java.lang.Class)" is null
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil1_19_R2.getDouble(ChipUtil1_19_R2.java:1123) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil1_19_R2.fromNMS(ChipUtil1_19_R2.java:1300) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil1_19_R2.lambda$getGoals$0(ChipUtil1_19_R2.java:144) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at be.isach.ultracosmetics.shaded.mobchip.abstraction.ChipUtil1_19_R2.getGoals(ChipUtil1_19_R2.java:144) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.updateMap(BukkitAI.java:36) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitAI.<init>(BukkitAI.java:31) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.shaded.mobchip.bukkit.BukkitBrain.getGoalAI(BukkitBrain.java:101) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.clearPathfinders(Pet.java:137) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.cosmetics.pets.Pet.onEquip(Pet.java:121) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.cosmetics.Cosmetic.equip(Cosmetic.java:89) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.cosmetics.type.CosmeticType.equip(CosmeticType.java:154) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:64) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.cosmetics.type.PetType.equip(PetType.java:31) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.menu.CosmeticMenu.toggleOn(CosmeticMenu.java:321) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.menu.CosmeticMenu.handleClick(CosmeticMenu.java:366) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.menu.CosmeticMenu.lambda$open$1(CosmeticMenu.java:136) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at be.isach.ultracosmetics.menu.Menu.onClick(Menu.java:132) ~[UltraCosmetics-3.0-DEV-b3b.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor240.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-345]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3161) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:58) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:23) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-345]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-345]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by datatags** [comment]
This and #76 are both MobChip bugs, so I'm working on a PR for MobChip that will fix these.
