### ISSUE TITLE
Error while opening a Treasure Chest

### ISSUE THREAD

**Issue by LatukaTV** [datatags/UltraCosmetics#96]
Ultra Cosmetics only give Money. Everytime i open a firework appears with this error Code, but not when Money is inside

Could not pass event PlayerInteractEvent to UltraCosmetics v2.9.4-RELEASE
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "this.power" is null
        at org.bukkit.craftbukkit.v1_19_R2.inventory.CraftMetaFirework.getPower(CraftMetaFirework.java:392) ~[paper-1.19.3.jar:git-Paper-362]
        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftFirework.setFireworkMeta(CraftFirework.java:66) ~[paper-1.19.3.jar:git-Paper-362]
        at be.isach.ultracosmetics.treasurechests.TreasureRandomizer.spawnRandomFirework(TreasureRandomizer.java:292) ~[UltraCosmetics-2.9.4-RELEASE.jar:?]
        at be.isach.ultracosmetics.treasurechests.TreasureRandomizer.giveRandomCosmetic(TreasureRandomizer.java:255) ~[UltraCosmetics-2.9.4-RELEASE.jar:?]
        at be.isach.ultracosmetics.treasurechests.TreasureRandomizer.giveRandomThing(TreasureRandomizer.java:177) ~[UltraCosmetics-2.9.4-RELEASE.jar:?]
        at be.isach.ultracosmetics.treasurechests.TreasureChest.onInter(TreasureChest.java:227) ~[UltraCosmetics-2.9.4-RELEASE.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor351.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-362]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:546) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:528) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1959) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1341) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1318) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1311) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1289) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[paper-1.19.3.jar:git-Paper-362]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-362]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LatukaTV** [comment]
i see a new info, i wont see ingame, what i get, and ultracosmetics doesnt realize that he gives me permissions for random gadgets. 

I Open a Chest:
It gives me a Firework,
it gives me a Random Permission for a Gadget,
i need to click the chest and the randomizer only stops when the chest gives me Money

my english is very bad sorry.

with 1 treasure chest i can get 20 Gadgets cause this error. the treasure chest only stops if it gives me money

**Comment by datatags** [comment]
Your Paper is out of date, this is not a bug in UltraCosmetics.
